Day 2: NumPy Practice Notebok

In [1]:
import numpy as np

1. Creating Arrays 

In [4]:
arr1 = np.array([1,2,3]) #rank 1 or one-dimensional array

In [7]:
arr2 = np.array([[1,2,3], [4,5,6]]) #rank 2 or two-dimensional array

In [14]:
print(arr1)
print(arr2)

[1 2 3]
[[1 2 3]
 [4 5 6]]


=> Checking the shapes of the array

In [8]:
print(arr1.shape)
print(arr2.shape)

(3,)
(2, 3)


In [9]:
arr_zeros = np.zeros((2,2)) #creating an array with all zero elements
print(arr_zeros)

[[0. 0.]
 [0. 0.]]


In [10]:
arr_ones = np.ones((2,1)) #creating an array with all one elements 
print(arr_ones)

[[1.]
 [1.]]


In [15]:
arr3 = np.array([[(1.5,2,3), (4,5,6)],[(3,2,1), (4,5,6)]], dtype = float) #creatng a 3D array 
print(arr3)

[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


In [16]:
print(arr3.shape)

(2, 2, 3)


In [31]:
arr_random = np.random.randint(0,10000000,(4,2,3)) #creating 3x2 2D dimensional array with random integer elements
print(arr_random)

[[[2021292 6123170 4013993]
  [4141228 3344842 9285195]]

 [[1046828 6435235 4898072]
  [5278231 9783447 4206456]]

 [[ 997023  881695 3151035]
  [9979677  440945  308677]]

 [[1425387 3423697  160357]
  [1395813 4095683 8734618]]]


In [32]:
arr_ide = np.eye(3) #creating an identity matrix of nxn size 
print(arr_ide) 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


2. Linear ALgebric Operations

In [33]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

In [35]:
print(np.dot(A,B)) #matrix multiplication

[[19 22]
 [43 50]]


In [40]:
A_Trans = A.T #making any vector/matrix transposed
print(A_Trans) 

[[1 3]
 [2 4]]


In [39]:
A_Inv = np.linalg.inv(A) 
print(A_Inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [41]:
A_Det = np.linalg.det(A) #finding determinant of any matrix
print(A_Det)

-2.0000000000000004


In [46]:
A_norm = np.linalg.norm(A)
print(A_norm)

5.477225575051661


In [44]:
arr = np.arange(1, 13) 
print(arr)
arr_reshaped = arr.reshape((3,4)) #changing shape of any array
print(arr_reshaped)
arr_flat = arr_reshaped.ravel() #flattens any array
print(arr_flat)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
