# Week 5_Day 1 : PyTorch Basics: Tensors & Autograd

In [3]:
import torch

print("Torch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

x = torch.tensor([1, 2, 3])
print(x)
print("x:", x)
print("x * 2:", x * 2)


Torch version: 2.9.1+cpu
CUDA available: False
tensor([1, 2, 3])
x: tensor([1, 2, 3])
x * 2: tensor([2, 4, 6])


Checking Shape and Data Types

In [6]:
x.shape


torch.Size([3])

In [7]:
x.dtype

torch.int64

In [8]:
y = torch.tensor([1.0, 2.0, 3.0])
y.dtype

torch.float32

Mathemetical Operation

In [9]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

a + b

tensor([5., 7., 9.])

In [10]:
a * b

tensor([ 4., 10., 18.])

In [11]:
a.mean()

tensor(2.)

Learnable Tensors

In [12]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

Autograd

In [13]:
x = torch.tensor(3.0, requires_grad=True)
y = x ** 2
y

tensor(9., grad_fn=<PowBackward0>)

In [14]:
y.backward() #backpropagation

In [15]:
x.grad #Inspect the gradient

tensor(6.)

Example - Linear Model Gradient

In [16]:
x = torch.tensor(4.0)
w = torch.tensor(2.0, requires_grad=True)

y = w * x
y.backward()

w.grad

tensor(4.)