# Week 5_Day 2 : Models, Layers & Loss Functions

## CONCEPT 1: nn.Module

In [1]:
import torch
import torch.nn as nn

class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self, x):
        return x

The structure:

- **__init__** → define the parts (layers)

- **forward()** → define how data flows through the parts

## CONCEPT 2: nn.Linear 

In [2]:
linear = nn.Linear(2, 1)   # 2 inputs -> 1 output

x = torch.tensor([[1.0, 2.0]])  # batch of 1 sample, 2 features
out = linear(x)

out

tensor([[1.4883]], grad_fn=<AddmmBackward0>)

## CONCEPT 3: forward()

In [3]:
class LinearModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(2, 1)
        
    def forward(self, x):
        return self.linear(x)

model = LinearModel()

x = torch.tensor([[1.0, 2.0],
                  [3.0, 4.0]])  # 2 samples, 2 features

pred = model(x)
pred

tensor([[-0.3732],
        [-0.4176]], grad_fn=<AddmmBackward0>)

## CONCEPT 4: Loss Functions

In [4]:
mse = nn.MSELoss()

pred = torch.tensor([[10.0],
                     [20.0],
                     [30.0]])

true = torch.tensor([[12.0],
                     [18.0],
                     [33.0]])

loss_value = mse(pred, true)
loss_value

tensor(5.6667)

### Loss 2: CrossEntropyLoss (Classification)

In [5]:
ce = nn.CrossEntropyLoss()

# 3 samples, 2 classes (class0, class1)
logits = torch.tensor([[2.0, 1.0],
                       [0.5, 1.5],
                       [1.0, 3.0]])

# correct class labels
true = torch.tensor([0, 1, 1])

loss_value = ce(logits, true)
loss_value

tensor(0.2512)

### HANDS-ON MINI TASK: Logistic Regression Classifier

In [6]:
# defining the model 
class LogisticRegressionModel(nn.Module):
    def __init__(self, n_features, n_classes):
        super().__init__()
        self.linear = nn.Linear(n_features, n_classes)
        
    def forward(self, x):
        return self.linear(x)  # logits

model = LogisticRegressionModel(n_features=2, n_classes=2)
model

LogisticRegressionModel(
  (linear): Linear(in_features=2, out_features=2, bias=True)
)

In [7]:
# creating a dataset
X = torch.tensor([[50.0, 600.0],
                  [30.0, 500.0],
                  [80.0, 720.0],
                  [25.0, 450.0]])

y = torch.tensor([1, 0, 1, 0])  # labels

In [8]:
# forward pass 
logits = model(X)
logits

tensor([[ 77.3198, 112.6959],
        [ 62.3821,  92.7599],
        [ 96.3403, 137.2344],
        [ 55.8260,  83.3046]], grad_fn=<AddmmBackward0>)

In [9]:
# computing loss 
criterion = nn.CrossEntropyLoss()
loss = criterion(logits, y)
loss

tensor(14.4641, grad_fn=<NllLossBackward0>)